# Use root/example as user/password credentials
version: '3.1'

services:
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - 27025:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: asdfasdf
      MONGO_INITDB_DATABASE: wiki
    networks:
      default:
        aliases:
          - wiki_mongo
